### ISSUE TITLE
Include subsection in event data

### ISSUE THREAD

**Issue by danielmcquillen** [pmitros/DoneXBlock#8]
Is there an easy way to include the subsection title in the data object passed to tracking? Knowing the name of the subsection a button was clicked in would be really helpful when passing this event on to things like Google Analytics. 

The event data currently includes the edx identifiers for chapter / section (by virtue of the page data that always appears in 'context' part of events), but those aren't much help to external resources that can't look up display names.

Thanks for any thoughts.

**Comment by OmarIthawi** [comment]
Hey @danielmcquillen, is this still an issue? If so, could you please submit a pull request?

Also, were you aware of the new https://github.com/edx/completion API?

**Comment by danielmcquillen** [comment]
@OmarIthawi Sorry, I never pursued using this XBlock after initial testing. I'll close this issue.
